from DNAToolkit import *
# import collections

data = 'CCCTAAGGTGCTTATGTTAGGGCGACGCCGGCCCTCTCCGGACAAACACATATACCTGAAACACCTCAATGGATTTATTTCTCAACATAACTGGGAACTCTTGGGCGGGGAGAACATTACGAATGTACTACATGCATAAAAACCACACTGCTGCGTTAACTTACGGAATCGTAGGTGTTCGGCATGGTTTACTCCGAACGCTCAGTCCTCTTCCCGTCGACACTTTTCCTACGTGGACGAAATAACGCCCCGGGGGTTCGGTGTTCCCCCCTGTGAAAGTTTCACCGGCTTATGGACAGTAGGTATGAGCGGAAGGGGCCGACTGTCTCGGCTTGAACACAGTCACACAGCCGTGCAATCCACGATGTTATGGACAATACTATTTCAAGCTGTTGAAACAATCTCCTCAAAGGAAGCGGAACTAGGGAGTATTATTGAATCAACGGCCCGAGCGCGGGAAGCACTCGCCATTCGCGCGTATTATATCATAACATCGCGTTCGTTAAAATTCCTAGGACGCCCGTCCAACGGCGGTCGGAGACTGTAGCGCTTCCGCTGCAGCAACTGCGTTTCGGCCCTCCTGCAAAGAGCATCCGCGTTAAGGTATGACCCTGATTCGAACAATCCTTATGTTCGATGGGCATGTTCTAATCTCCGACACAGGGAACTGCGGAAACCGACCAACCGTGTCTGCATGCGGGACGGCGCTGTCCAGCTCGACACGAATAAACATCAACCTCCCTTGGTGATGTTCAGGTCGTCAGGGTGACGCGTTCCTTGGGGTGCGCTCGCTGCGGAACTGCGTTGGACAGATACTCCGACATTAAGTTTTCGCTTCC'

print(verdnastr(data))

#Define the function to count all nucleotides numbers
# def count_nucleotides(dnastr):
#     return dict(collections.Counter(dnastr))

#Easier to understand function to count all nucleotides numbers

# def count_nucleotides(dnastr):
#     dnadic = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
#     for nuc in dnastr:
#         dnadic[nuc] += 1
#     return dnadic

#How its asked in problem( Simple version)
def count_nucleotides(data):
    a = data.count('A')
    t = data.count('C')
    g = data.count('G')
    c = data.count('T')
    return print(f'{a} {t} {g} {c}')

if __name__ == '__main__':
    print(count_nucleotides(data))

