Nucleotides = ['A','T','G','C']
DNA_reverse = {'A':'T','T':'A','G':'C','C':'G'}


data = 'CCCTAAGGTGCTTATGTTAGGGCGACGCCGGCCCTCTCCGGACAAA'

raw_dna = 'TGTATCCGGTCGACTCTTTCTCATGCAGCCGACAGCCAGTTAA'


rev_data = 'TTGTCGCCGAATTAATTCCCTCCCTCGTACACATATCAAAAT'